### ISSUE TITLE
Invalid Configs

### ISSUE THREAD

**Issue by Stell-r** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#231]
AutoCatcher giving me the same error code

Hi guys im new to this community, just need some help to setup the self bot as I followed the instructions but cant seem to figure out what to do with this error code

It seems to repeat the same thing no matter what ive tried so ive come over here for some help (screenshots attatched)

Windows 10 Pro
Python 3.9.5 
Thanks![](https://cdn.discordapp.com/attachments/728246934070100084/840277751286071306/unknown.png)

**Comment by Hyperclaw79** [comment]
You're missing a comma in your configs.
But that being said, the code in this public version is 3yrs old and not maintained like the Premium Version. It might not work with the correct configs either.
There is a long-term plan to migrate this public version to Refactor version as well with limited features (excluding autocatcher).
