### ISSUE TITLE
Improper Token

### ISSUE THREAD

**Issue by NroxpTheDev** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#233]
My Bot Token Is Correct But It Is Saying Incorrect
![Screenshot_20210518_212700](https://user-images.githubusercontent.com/76842211/118682167-ea570300-b81f-11eb-9f8d-f7e36aa34116.jpg)

**Comment by Hyperclaw79** [comment]
The response you get in the screenshot is from discord itself, so if it says it is invalid, then that must be the case. So, this is not the case of the bot not working, but rather a wrong token being used.
How exactly did you get your token? Do you have 2 Factor Authentication enabled?
Are you sure you're using a user token and not a discord bot token?

**Comment by NroxpTheDev** [comment]
Using A User Token Will Host My Account But I Want To Host A Discord Bot

**Comment by Hyperclaw79** [comment]
That's not how selfbots work lol. You think discord bots can play poketwo?  😂
