### ISSUE TITLE
Not showing online 

### ISSUE THREAD

**Issue by Legend2412** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#234]
I did all the steps ,but my not is not online ,pls help

**Comment by Hyperclaw79** [comment]
I won't be able to help you without any debug information. Please follow the issue template and post the relevant details and screenshots.
Provide as much information as possible.

**Comment by Legend2412** [comment]
See I did all the steps in tutorial but the bot is still showing offline 
![IMG_20210527_172701](https://user-images.githubusercontent.com/84903353/119822393-3a655200-bf11-11eb-9ec0-9a7a9ca46cb4.jpg)
This is config.json
{
   "token": ""cencor token"",
   "command_prefix": "P^",
   "priority": [
      "Groudon",
      "Mew",
      "Machop",
      "Staryu"
   ],
   "avoid": [],
   "catch_rate": 90,
   "delay": 3,
   "delay_on_priority": false,
   "restrict_duplicates": true,
   "max_duplicates": 2,
   "blacklists": [],
   "whitelists": [],
   "blacklist_guilds": [382316968394620938],
   "whitelist_guilds": [],
   "autolog": true,
   "update_checker": true,
   "auto_update": true,
   "autocatcher": false,
   "priority_only": false
}
Idk what should I do to make it online

**Comment by Hyperclaw79** [comment]
You're mistaking between a normal Discord bot and a Selfbot.
Selfbot is basically an automated user account.
 You can't catch pokemons with a normal Discord bot.

**Comment by Legend2412** [comment]
What is the bot token in the config.json

**Comment by Hyperclaw79** [comment]
It's your user account's token. Search about selfbot tokens
