### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by tetron22** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#238]
commands are not working and crashes every minute. can't use it

**Comment by Hyperclaw79** [comment]
1. Follow the issue template provided. Just saying "not working" doesn't provide any relevant information.
2. This code is 3yrs old now and unsupported. It most likely won't work either way. Only Premium Version is supported and regularly updated.
3. Read the closed issues first before opening a new issue.

I'm closing this for now, but feel free to reopen with updated information if relevant.

**Comment by tetron22** [comment]
i got the link from my someone, as i have the program i just needed some help. How rude you are for simple request!!
sheesh

**Comment by Hyperclaw79** [comment]
Are you out of your mind kid??
First of all you don't follow the issue template. You don't even read the Readme.
I merely just pointed out the facts and you see that as rude?
There's a minimum decency that's expected on GitHub. Please don't ruin the atmosphere with your immaturity and ignorance.
