### ISSUE TITLE
Autocatcher 

### ISSUE THREAD

**Issue by krishgoyal** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#239]
@hyperclaw , i found your premium version on discord URl , it is drive link right?
it seems good can you tell me how to start it as i don't see any video guide in it. any link pls?
(If anyone need it for free - dm me at Cinnabun#6204 ) ❣️ 

also. your program are being share for free. i will tell my friends to star your repo as there is one more but that seems more Op tho. (can't afford $1 otherwise will buy)
your stars are less so i think people don't like it or idk it is urs.

but anyways i will surely leave a great Review here after you share the guide video as you promise to paid clients.

**Comment by Hyperclaw79** [comment]
You expect me to provide you free support for something you didn't buy from me?
My repos don't lack stars mate, it was the first one to even have these many stars in a legal way.
All your "OP" repos are using illegal scripts to boost themselves and will be banned from GitHub at any time.

You plebs don't have the technical skills to write even a beginner level code and are using such underhanded methods.
All I can feel for you guys is mere pity.
