### ISSUE TITLE
Poketwo

### ISSUE THREAD

**Issue by Kittencky** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#240]
Mail address?

**Comment by Hyperclaw79** [comment]
Someone reported my main account so I don't have access to it. For now, you can email me if you want to purchase it.

**Comment by Jiggy2** [comment]
how do i find your email
because i want to buy the premium version

**Comment by Hyperclaw79** [comment]
This is my mail:
***@***.***
