### ISSUE TITLE
Autocatcher not working

### ISSUE THREAD

**Issue by Tenz123-bit** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#244]
# ![image](https://user-images.githubusercontent.com/85326081/135184624-cc1bb858-4bc7-4ad6-bac4-573110e901fe.png)
![image](https://user-images.githubusercontent.com/85326081/135184662-42af215f-c36c-47c1-8a57-263e62ebfd43.png)

**Comment by Hyperclaw79** [comment]
As clearly stated in the Readme, Autocatcher is Premium Version only and won't work in the public version.
