### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by FlyRobo** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#262]
i have done all the steps correctly (like running setup.bat, pasting the token) but whenever i run "run.bat" it gives me an error

![image](https://user-images.githubusercontent.com/86090322/186706955-a99f93dd-b0bc-4c65-ab97-07546064e30e.png)

idk wat to do so yeah

**Comment by Hyperclaw79** [comment]
The public version is not maintained anymore, so it will not work.

**Comment by FlyRobo** [comment]
So is there nothing i can do?

**Comment by Hyperclaw79** [comment]
Purchasing the premium version is an option.
