### ISSUE TITLE
errno2 no such file or directory

### ISSUE THREAD

**Issue by iRcar** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#263]
# Title:  ErrorName 2 no such file or directory

# Body:

## Problem:
Good, Python is already added to the Path!
python: can't open file 'check_ver.py': [Errno 2] No such file or directory

Press any key to continue ...

## Steps to Reproduce:
i added python path to root folder, ensured the .py used in both run and setup bat files were present, neither bat say the related .py files

## Specs.
**OS**: WIN 11
**Bot Version**: 8.5
**Python Version**:  3.8.10

**Comment by iRcar** [comment]
opening the files directly using IDLE let me bypass the on going issue and get the app working

**Comment by Hyperclaw79** [comment]
Tracking this conversation internally since it's for premium version.
