### ISSUE TITLE
Error while running run.bat

### ISSUE THREAD

**Issue by UnknownX0001** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#264]
![image](https://user-images.githubusercontent.com/88265081/213725861-35871f97-45a8-4e7c-a336-32137fc2f99e.png)

Well i suppose its some error with intents i would be glad if you help me out as soon as possible, thanks.

**Comment by Hyperclaw79** [comment]
Public Version is very old and not supported anymore.
