### ISSUE TITLE
Bot doesn't work as intended

### ISSUE THREAD

**Issue by Cosmoverz** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Autocatcher#266]
When I run it in my linux terminal, after I followed all the instructions carefully. The bot doesn't run when there is a new spawn and in the terminal it shows this warning, `2023-06-20 12:35:58 WARNING  discord.state Member list scraping failed for 837044030633934918 (Failed to automatically choose channels; please specify them manually).
2023-06-20 12:35:58 WARNING  discord.state Member list scraping failed for 869911963608698880 (Failed to automatically choose channels; please specify them manually).`

**Comment by Hyperclaw79** [comment]
Pokeball is not supported anymore.
